name: fauzi
favicon: null
layout_spectrum: 0.8700080825947225
typography_spectrum: 0.060318607138469815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7727663689292967
  lightness: 0.9896149733103812
  saturation: 0.8586175229866058
  rhythmicContrast: 0.047708596801385283
purpose: []
